### ISSUE TITLE
Install.py crashes when called from external directories

### ISSUE THREAD

**Issue by TUArjun** [Hackademic/hackademic#196]
Issue:

When install.py is called from any other external directory, it crashes with the following error message.

```
test@test ~/Documents/Project/hackademic python ContainerManager/install.py 
[+] Docker has successfully installed.
[+] Now Pulling Image. This could take sometime. Please wait..
[+] Installing Docker and necessary supporting plugins
[+] This could take some time. Please wait ...
[+] Building and Configuring Docker
Traceback (most recent call last):
  File "ContainerManager/install.py", line 127, in <module>
    main()
  File "ContainerManager/install.py", line 121, in main
    docker.build_docker()
  File "ContainerManager/install.py", line 104, in build_docker
    self.install.install_log('Docker Build error: \n' + str(exception))
  File "/home/testify/Documents/Project/hackademic/ContainerManager/logging_manager.py", line 53, in install_log
    logger = self.create_logger('install_log', 'install.logs')
  File "/home/testify/Documents/Project/hackademic/ContainerManager/logging_manager.py", line 35, in create_logger
    ch = logging.FileHandler(filename=self.path + '/hackademic-logs/'+filename)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/test/Documents/Project/hackademic/hackademic-logs/install.logs'
``` 

Solution :

As seen in the error message, the error occurs due to fact that the location of log file is not accurately depicted within the code. By making the location of the log file independent of the location from which it is called, this issue can be fixed.

**Comment by a0xnirudh** [comment]
Yes, it seems I used `os.getcwd()` instead of using the absolute path of the `install.py` file.

**Comment by TUArjun** [comment]
Issue :

When calling install.py from external directory, the following error is encountered.
```
2016-02-25 18:10:21,274 - install_log - ERROR - Docker Build error: 
Command 'docker build -t hackademic .' returned non-zero exit status 1
Traceback (most recent call last):
  File "ContainerManager/install.py", line 101, in build_docker
    stderr=subprocess.STDOUT, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'docker build -t hackademic .' returned non-zero exit status 1
```

Solution:

While looking at the install.py file, it can be identified that the build location for the docker image is taken as the current directory. This can be fixed by making the build path dependent on the location of the file, rather than an absolute location.

**Comment by a0xnirudh** [comment]
This is because when calling from external directory, it will look for the docker file in the current path and not on the correct location. Thanks for the fix !
